### ISSUE TITLE
Building 'PvQv_C'?

### ISSUE THREAD

**Issue by nwilliams-kobold** [tsutterley/spatial-interpolators#1]
I've been looking for python implementations of tension splines for years, so I'm keen to try out your code. But I am having some problems finding the right commands to build PvQv_C.

I tried:
* `pip install .` (which seems to run without error, but doesn't fix the `No module named 'PvQv_C'` error)
* `python setup.py build_ext --inplace` followed by `python setup.py install` (which also seems to run without error, but then I get an import error on `spatial_interpolators` instead of `PvQv_C`)
* importing and installing pyximport first (which seems to do nothing useful)

I'm on Python 3.8.8.

**Comment by tsutterley** [comment]
Hi @nwilliams-kobold 
sorry about that.  I was reworking the cython import last time I worked on this project and needed to do a couple of extra changes.  I think I have things fixed for you in PR #2 .  I also added a quick flake8 CI to try to catch things like this.
Cheers,
Tyler

**Comment by nwilliams-kobold** [comment]
Perfect thanks. To confirm, this now installs fine just with `pip install .`
