### ISSUE TITLE
Scipy cdist can replace distance_matrix for speed

### ISSUE THREAD

**Issue by nwilliams-kobold** [tsutterley/spatial-interpolators#3]
I'm getting some great results from the biharmonic spline code, but found there is an easy method to speed things up substantially.

Use `scipy.spatial.distance.cdist` in place of the `distance_matrix` function.

With the addition of ```import scipy.spatial.distance as distance```,

```Rd=distance_matrix(np.array([xs, ys]), np.array([xs, ys])) # Original```
becomes
```Rd = distance.cdist(np.array([xs, ys]).T, np.array([xs, ys]).T) # Updated```

and 
```Re=distance_matrix(np.array([XI.flatten(),YI.flatten()]), np.array([xs,ys])) # original```
becomes
```Re = distance.cdist(np.array([XI.flatten(),YI.flatten()]).T, np.array([xs,ys]).T) # Updated```

Each call speeds up by a factor of 10.

**Comment by tsutterley** [comment]
PR is in.  Thanks for the upgrade!

**Comment by tsutterley** [comment]
I just put in some work today to add some documentation and other fixes.  The changes will break backwards compatibility as I made most of the keyword arguments lower case.  Let me know if this is a problem.

**Comment by tsutterley** [comment]
Also @nwilliams-kobold would you like to be added to the contributors list?

**Comment by nwilliams-kobold** [comment]
Thanks for the update! No need to add me. My edit was trivial.
